processChildParent: processChildParent.o
	gcc -g -Wall -o processChildParent processChildParent.o

processChildParent.o: processChildParent.c
	gcc -g -Wall -c processChildParent.c

clean:
	rm *.o processChildParent
