all: Prak02_1 Prak02_2 Prak02_3 Prak02_4

Prak02_1: Prak02_1.o
	gcc -g -std=c99 -Wall -o Prak02_1 Prak02_1.o 

Prak02_1.o: Prak02_1.c
	gcc -g -std=c99 -Wall -c Prak02_1.c

Prak02_2: Prak02_2.o
	gcc -g -std=c99 -Wall -o Prak02_2 Prak02_2.o 

Prak02_2.o: Prak02_2.c
	gcc -g -std=c99 -Wall -c Prak02_2.c

Prak02_3: Prak02_3.o
	gcc -g -std=c99 -Wall -o Prak02_3 Prak02_3.o 

Prak02_3.o: Prak02_3.c
	gcc -g -std=c99 -Wall -c Prak02_3.c

Prak02_4: Prak02_4.o
	gcc -g -std=c99 -Wall -o Prak02_4 Prak02_4.o 

Prak02_4.o: Prak02_4.c
	gcc -g -std=c99 -Wall -c Prak02_4.c

clean: 
	rm *.o  Prak02_1 Prak02_2 Prak02_3 Prak02_4

